### ISSUE TITLE
Forge reported an error

### ISSUE THREAD

**Issue by lyy2182** [gisellevonbingen-Minecraft/BossTools-Addon#144]
### Minecraft Version

1.18.2

### Forge Version

40.2.14

### Space-BossTools or Beyond Earth Version

1.18.2-7.0SNAPSHOT

### Addon Mod Version (This Mod)

1.16.5-2.20

### The details

[crash-2023-12-24_22.34.35-fml.txt](https://github.com/gisellevonbingen-Minecraft/BossTools-Addon/files/13762106/crash-2023-12-24_22.34.35-fml.txt)
[debug.log](https://github.com/gisellevonbingen-Minecraft/BossTools-Addon/files/13762107/debug.log)
[latest.log](https://github.com/gisellevonbingen-Minecraft/BossTools-Addon/files/13762108/latest.log)

Error loading mods 
1 error has occurred during loading
Beyond Earth: Giselle Addon (beyond_earth_giselle_addon) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

**Comment by gisellevonbingen** [comment]
Sorry, Beyond Earth 7.0 version is not supported now.

**Comment by gisellevonbingen** [comment]
I was tried fix code to support 7.0 SNAPSHOT.
And I decided that can't support Beyond Earth 7.0 SNAPSHOT version following these reasons.
1. Source code missing.
- Can't found Beyond Earth source code about 7.0
2. Too many code changed.
- It may seem like an excuse, but event system and compatibility with other mode, etc. codes are broken.
